version: "3.8"

services:
  web:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - my_network

  php:
    build:
      context: ./
    container_name: php_container
    volumes:
      - ./:/var/www/html
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
